version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    restart: unless-stopped
    container_name: ducatus_bot_deposits
  redis:
    image: 'redis:latest'
    container_name: redis-server
    ports:
      - '6379:6379'