version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    restart: unless-stopped
    container_name: ducatus_bot_deposits
    volumes:
      - ./.docker/logs:/code/logs
  redis:
    image: 'redis:7.4.1'
    container_name: redis
    ports:
      - '6379'
    restart: unless-stopped
    volumes:
      - ./.docker/redis-data:/data