BALANCE_COMMAND = 'balance'
STOP_COMMAND = 'stop'

TIMEOUT = 60
CONNECT_TIMEOUT = 30.0
READ_TIMEOUT = 60.0
WRITE_TIMEOUT = 60.0

REDIS_BALANCE_KEY = 'balance'
REDIS_CHAT_IDS_KEY = 'chat_ids'
REDIS_DATETIME_KEY = 'last_alert'
REDIS_DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'
